# Generated by Django 3.1.7 on 2021-03-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.IntegerField()),
                ('balance', models.FloatField()),
                ('amount', models.FloatField()),
                ('type', models.IntegerField()),
            ],
        ),
    ]
