# Generated by Django 3.1.7 on 2021-03-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0002_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='time',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
